// <auto-generated />
namespace CTM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _038 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_038));
        
        string IMigrationMetadata.Id
        {
            get { return "201703200343464_038"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
