// <auto-generated />
namespace CTM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _036 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_036));
        
        string IMigrationMetadata.Id
        {
            get { return "201702090148334_036"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
